### ISSUE TITLE
Bug with story-id detection if URL is ended with slash

### ISSUE THREAD

**Issue by AndyScull** [MRH4287/FFNetParser#47]
Hi,
I noticed strange behavior, it depends on ending of URL, for example - 
1) In search list, I set category for some story
2) Enter this story reading page, category is correct for all chapters
3) Delete last part of URL, so it would end with /
4) Shown category is shifted by -1, to one above.

Now, 5) If on that page (ending with /) I change category, it is added as custom highlight, in config export I see two entries in "highlighter":
-  for id "10594533" (previous entry which works across all chapters, URL must not end with slash)
- and custom entry for "/s/10594533/1/":{ "custom":{"name":"/s/10594533/1/", etc etc

**Comment by MRH4287** [comment]
Hi,
that happens when you write `/\/s\/([0-9]+)\/([0-9]+)\/(.+)/` instead of `/\/s\/([0-9]+)\/([0-9]+)\/(.*)/`
The RegExp searched for something on the end ... but in this case, there did not need to be any ...

I'll change it in the next update .. but i won't make a new Version just because of this ^^

Thanks for the report :)

**Comment by AndyScull** [comment]
Thanks!
I changed the regexp on my machine, so don't worry about updating the official build

**Comment by MRH4287** [comment]
Did you compile a new Version from the source or did you change the minimized JavaScript?
It seems like you know what you are doing, so its fine either way :)

I wouldn't suggest a rookie to change minimized Code though .. as it might alter the Behaviour too much :P
